spring:
  jackson:
    time-zone: GMT+8
  freemarker:
    charset: UTF-8
    suffix: .ftl
    content-type: text/html;charset=UTF-8
    template-loader-path: classpath:/templates
    check-template-location: true
    enabled: true
    expose-spring-macro-helpers: true
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/cloudaping?characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        # 最大空闲连接
        max-idle: 8
        # 最小空闲链接
        min-idle: 0
        # 最大连接数（负数表示没有限制）
        max-active: 8
        # 最大阻塞等待时间（负数表示没有限制）
        max-wait: 0
    timeout: 5000
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录
      additional-paths: resources/**,static/**,templates/**
      #该目录下的内容修改不重启
      exclude: data/**